// 9 MME + 20,50,200 MMA (welliott_trading)

// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © wellrats

//@version=6
indicator('9 MME + 20,50,200 MMA', overlay = true)

//Input Menus
Input1 = input(9, 'Primeira EMA')
Input2 = input(20, 'Segunda MMA')
Input3 = input(50, 'Terceira MMA')
Input4 = input(200, 'Quarta MMA')

shortest = ta.ema(close, Input1)
short = ta.sma(close, Input2)
longer = ta.sma(close, Input3)
longest = ta.sma(close, Input4)

//cumulativePeriod = input(20, "VWAP Period")

// typicalPrice = (high + low + close) / 3
// typicalPriceVolume = typicalPrice * volume
// cumulativeTypicalPriceVolume = math.sum(typicalPriceVolume, cumulativePeriod)
// cumulativeVolume = math.sum(volume, cumulativePeriod)
// vwapValue = cumulativeTypicalPriceVolume / cumulativeVolume

// plot(vwapValue, "VWAP", color = color.new(color.aqua, transp=0))
plot(shortest, 'Primeira EMA', color = color.new(color.blue, transp = 0), linewidth = 2)
plot(short, 'Segunda MMA', color = color.new(color.green, transp = 0), linewidth = 2)
plot(longer, 'Terceira MMA', color = color.new(color.orange, transp = 0), linewidth = 2)
plot(longest, 'Quarta MMA', color = color.new(color.black, transp = 0), linewidth = 2)
