// KJS -- Max Volume Candle

// 
// © ksabobo

//@version=6

indicator('KJS -- Max Volume Candle', shorttitle = 'MVC-ID', overlay = true)



var int leftIndexTime = chart.left_visible_bar_time
var int rightIndexTime = chart.right_visible_bar_time
var int leftIndex = 0
var int rightIndex = 0
var int visible_bars = 0

if leftIndexTime <= time and time <= rightIndexTime
//     visible_bars := visible_bars + 1
//     visible_bars

// Number of bars to include
look_ahead_bars = visible_bars


// Initialize an array to hold the volume values
var float highest_volume = na
var array<float> volume_array = na

if bar_index >= look_ahead_bars
    // Initialize the array with the correct size and populate it
//     volume_array := array.new_float(look_ahead_bars + 1, na)
    for i = 0 to look_ahead_bars - 0 by 1
//         array.set(volume_array, i, volume[look_ahead_bars - i]) // Get volume from the current bar and forward-looking bars

    // Resize the array to remove the last value (FIRST BAR OFF CHART ON LEFT SIDE OF SCREEN)
//     array.remove(volume_array, 0) // Remove the last value by resizing to exclude it

    // Get the maximum volume from the array
//     highest_volume := array.max(volume_array)
//     highest_volume


// Create color variables
// var color BULL_BODY_COLOR = color.yellow
// var color BEAR_BODY_COLOR = color.purple
// var color BULL_BODY_COLOR = input.color(color.yellow, title = 'Bullish Body Color', group = 'Select Body Color', inline = 'Bull')
// var color BEAR_BODY_COLOR = input.color(color.purple, title = 'Bearish Body Color', group = 'Select Body Color', inline = 'Bear')
var color BULL_BODY_COLOR = #0039ff
var color BEAR_BODY_COLOR = #ffe500
var color bar_color = na


// Function to determine if current bar has highest volume
is_highest_volume = volume == highest_volume

// Determine candle direction
is_bullish = close > open

// Set the candle color based on conditions
// bar_color := na
if is_highest_volume
//     bar_color := is_bullish ? BULL_BODY_COLOR : BEAR_BODY_COLOR
//     bar_color


// // Plot colored bars using na() function
barcolor(bar_color)

// plotchar(is_highest_volume, "Highest Volume", "•", location.top)
// plotcandle(open, high, low, close, color = bar_color, bordercolor = border_color)

// // Add label on the last bar showing visible bars count
// if barstate.islast
//     label.new(x=bar_index[visible_bars - 3], y=high, text="Visible Bars: " + str.tostring(visible_bars), style=label.style_label_down, color=color.blue, textcolor=color.white, size=size.normal)
