// Volumatic Support/Resistance Levels [BigBeluga]

// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International  
// https://creativecommons.org/licenses/by-nc-sa/4.0/
// © BigBeluga

//@version=6
indicator("Volumatic Support/Resistance Levels [BigBeluga]", overlay = true)

// ＩＮＰＵＴＳ ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――{

length = input.int(25, "Length")
upper_threshold = input.int(80, "Resistance Max Volume %", maxval = 100, minval = 50, inline = "sup"), sup_col = input.color(color.rgb(28, 194, 114), "", inline = "sup")
lower_threshold = input.int(80, "Support Max Volume %", maxval = 100, minval = 50, inline = "res"), res_col = input.color(color.rgb(206, 37, 37), "", inline = "res")
bars_threshold = input.int(50, "Bars Max Volume %", maxval = 100, minval = 50, inline = "bar"), bar_col = input.color(color.rgb(255, 145, 55), "", inline = "bar")


var upper1 = float(na)
var upper2 = float(na)
var lower1 = float(na)
var lower2 = float(na)
// }


// ＣＡＬＣＵＬＡＴＩＯＮＳ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――{

h = ta.highest(length)
l = ta.lowest(length)

n_vol = volume / ta.percentile_linear_interpolation(volume, 500, 100)*100

if h[1] == high[1] and high < h 
//     upper1 := h 
//     upper2 := h 

if l[1] == low[1] and low > l 
//     lower1 := l 
//     lower2 := l 

atr = ta.atr(200) / 100
upper_col = upper1 != upper1[1] ? color(na) : res_col 
lower_col = lower1 != lower1[1] ? color(na) : sup_col
// }


// ＰＬＯＴ ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――{

plot(upper1, "Resistance", color = upper_col)
ph1 = plot(upper1 + atr*n_vol, color = na, editable = false)
ph2 = plot(upper2 - atr*n_vol, color = na, editable = false)

upper_fill = upper1 != upper1[1] ? na : color.from_gradient(n_vol, 0, 100, color.new(res_col, 80), res_col)

fill(ph1, ph2, upper_fill)

plot(lower1, "Support", color = lower_col)
pl1 = plot(lower2 + atr*n_vol, color = na, editable = false)
pl2 = plot(lower2 - atr*n_vol, color = na, editable = false)

lower_fill = lower1 != lower1[1] ? na : color.from_gradient(n_vol, 0, 100, color.new(sup_col, 80), sup_col)

fill(pl1, pl2, lower_fill)

plotshape(n_vol > lower_threshold ? lower2 - atr*n_vol : float(na), "Max Volume Support", shape.circle, location.absolute, color = sup_col, size = size.tiny)
plotshape(n_vol > lower_threshold ? lower2 + atr*n_vol : float(na), "Max Volume Support", shape.circle, location.absolute, color = sup_col, size = size.tiny)

plotshape(n_vol > upper_threshold ? upper2 + atr*n_vol : float(na), "Max Volume Resistance", shape.circle, location.absolute, color = res_col, size = size.tiny)
plotshape(n_vol > upper_threshold ? upper2 - atr*n_vol : float(na), "Max Volume Resistance", shape.circle, location.absolute, color = res_col, size = size.tiny)

barcolor(n_vol > bars_threshold ? bar_col : na)
// }
